Enable automatic branch deletion upon successful merge
eclipse-windowbuilder/.eclipsefdn pull request #1
Opened 2024-01-29 20:16 UTC by ptziegler

This should hopefully remove the overhead of manually clicking the "Delete branch" button.

2024-01-29 20:28 UTC, fredg02 approved these changes

2024-01-29 20:32 UTC, fredg02 commented on otterdog/eclipse-windowbuilder.jsonnet
> -      delete_branch_on_merge: false,
You can remove this line, since the default is `true`.

2024-01-29 20:32 UTC, fredg02 commented on otterdog/eclipse-windowbuilder.jsonnet
> -      delete_branch_on_merge: false,
You can remove this line, since the default is `true`.

2024-01-29 20:33 UTC, fredg02 requested changes
See comments.

2024-01-29 21:30 UTC, netomi commented
just fyi and to avoid unexpected results: the setting delete_branch_on_merge applies strictly to branches in the repo that is targeted by the PR. So if you create a PR from a fork, the branch in your fork will not be deleted after a successful merge and you still have to delete it manually. If you oth, create the branch to be merged in the same repo, the branch will be deleted automatically afterwards. Its quite handy for dependabot PRs which are created in the same repo, but not that useful for workflows where you mainly create PRs in forks.

2024-01-30 06:51 UTC, ptziegler commented
> So if you create a PR from a fork, the branch in your fork will not be deleted after a successful merge and you still have to delete it manually.

That's a good point and how we usually handle branches. Meaning that this change will likely not help in any meaningful way.
And for the forks, I can simply set the "delete on merge" flag in the GitHub settings of the forked repository, without having to modify this configuration here.

Thank you both for your input. In that case, I'll simply close this PR.

2024-01-30 06:51 UTC, closed without merging